# Generated by Django 5.1 on 2024-09-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='text',
        ),
    ]
